Baidu:
  AccessKey: ALTAKJ0b68ZR2DYTcomAxjo3kp
  SecretKey: 6a06b1b9ccd04880a35c44a769608c5f

Wangsu:
  AccessKey: 7a7VWPGTL2cWgzJ5SxQqhvKztxQQlHOk4I55
  SecretKey: x9rG3E3XqP3WgPoCjosB07qxi3UV4eOGgTI5dtYzUaLu9TR9STsYsgkwj9hHVU4J

Alibaba:
  AccessKey: LTAI5tGqjqzRN9qscWLicoz5
  SecretKey: r98gAYTFPKo8LaGMGakjarDEms60ip
